CREATE TABLE SpaceWeapons(
	SKU CHAR(6) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100),
	WEIGHT DOUBLE,
	POWER INT
);

INSERT INTO SPACEWEAPONS
	(SKU, NAME, WEIGHT, POWER)
VALUES
	('55-001', 'Laser Cannon', 22.5, 70);
	
SELECT * FROM SPACEWEAPONS;

DROP TABLE SPACEWEAPONS;