SELECT * FROM COFFEE WHERE Price > 9 AND PRICE < 10;

SELECT * FROM Coffee WHERE Description LIKE '%Dark%' AND PRICE >= 10;

SELECT * FROM Coffee WHERE Description LIKE '%Dark%' OR Description LIKE '%Decaf%';

SELECT * FROM Coffee WHERE ProdNum LIKE '2_-00%';

SELECT Upper(Description) FROM Coffee;

SELECT * FROM COFFEE ORDER BY PRICE;

SELECT * FROM COFFEE ORDER BY PRICE DESC;

SELECT AVG(PRICE) FROM Coffee;
SELECT SUM(PRICE) FROM Coffee;

SELECT Description, 2 * Price FROM Coffee;
SELECT MAX(PRICE) FROM Coffee;
SELECT DESCRIPTION FROM Coffee WHERE PRICE = 18.45;
SELECT MIN(PRICE) FROM Coffee;

SELECT COUNT(*) FROM Coffee;
